### ISSUE TITLE
点击发音按钮无法读出发音

### ISSUE THREAD

**Issue by VicWong6** [codethereforam/ChaZD#4]
首先感谢作者完善的这款插件，但是在查词后点击发音按钮无法发音，切换到自动发音也不行。请问是我自己设置的问题还是什么BUG，重启了Chrome也不行，一下是我的设置截图。万分感谢
![image](https://user-images.githubusercontent.com/30918648/35321185-6d887e20-0121-11e8-808d-163f4b6d4a5e.png)

**Comment by codethereforam** [comment]
@Wangsh6166 
- 我的系统是ubuntu，最近使用v1.2.1一直没问题
- 英文是可以发音的，中文不可以，你是哪个不可以发音
- 用你的设置，在我ubuntu测试了v1.0.0到v1.2.1，都可以发音
- 用win10测试了v1.2.1, 也可以正常发音
- 如有问题，请指出你系统版本, chrome版本和ChaZD release版本

**Comment by VicWong6** [comment]
我又测试了下，中文和英文的发音都不行。

- 系统：win10 

- Chrome版本：60.0.3112.78  GreenChrome 6.3.3

- ChaZD：v1.2.1
会不会是我用的免安装版本的Chrome的原因？

**Comment by codethereforam** [comment]
@Wangsh6166 
- 测试
    我用GreenChrome 6.4.2测试了下，还是没问题，我测试的页面是https://en.wikipedia.org
- 可能原因
我在原作者项目issues搜了下，有人反映过在github等网站无法发音。你试试英文维基百科等其他网页，试试能不能发音。我有空的时候尝试解决一下在github等界面无法发音的bug。
- 其他原因
如果不是上述原因，ctrl+shift+j把报错信息截图给我看下。

**Comment by codethereforam** [comment]
@Wangsh6166 
- 已解决在github等部分网站无法发音 (commit: f76f59c, release: v1.2.2)
- 不知道有没有解决你的问题

**Comment by VicWong6** [comment]
感谢作者，确实是因为在github上面才会报错，在其他网站能正常发音的。我下载了最新版本，github也能发音了。真心感谢
这是js报错的具体提示：
![clipboard](https://user-images.githubusercontent.com/30918648/35551685-37a10c92-05cb-11e8-86cc-8db2e99ea775.png)

**Comment by codethereforam** [comment]
has fixed in commit f76f59c
