### ISSUE TITLE
文档描述可能有误。

### ISSUE THREAD

**Issue by cmygit** [codethereforam/ChaZD#7]
安装描述中说到：
“如果不支持，将crx文件扩展名改为zip并解压，在chrome://extensions/勾选开发者模式，接着在 Chrome 设置拓展的地方，点击加载未打包的拓展。详细步骤见chrome怎么安装非官方市场的插件？ - 小赖的回答。”

改成了zip文件，用压缩工具打开是报错的。
![zip](https://user-images.githubusercontent.com/29950541/39103639-7bf1f286-46de-11e8-86f9-e9c04c7c3a97.png)

改成了rar文件，可以成功解压缩，并且安装。
![image](https://user-images.githubusercontent.com/29950541/39103651-94ec3d28-46de-11e8-8a08-d3b9a1347c7b.png)

不过不确定这是不是个例。
如果同样问题的朋友，可试试改成rar再解压缩。

**Comment by xiaohundun** [comment]
刚好碰到了，还在纳闷，然后就看到了，good！

**Comment by codethereforam** [comment]
可能和操作系统、解压工具有关，我用zip没问题
